name: Sync with Hugging Face

on:
    push:
        branches:
            - master

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # Ensure full clone to avoid shallow update issues
            - name: Install Git LFS
              run: sudo apt-get install git-lfs
            - name: Install Hugging Face Hub
              run: pip install huggingface_hub
            - name: Configure Git Credentials
              run: |
                  git config --global credential.helper store
                  echo "https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co" > ~/.git-credentials
            - name: Sync to Hugging Face
              env:
                  HF_TOKEN: ${{ secrets.HF_TOKEN }}
                  HF_USERNAME: ${{ secrets.HF_USERNAME }}
              run: |
                  git lfs install
                  huggingface-cli login --token $HF_TOKEN --add-to-git-credential
                  git remote add huggingface https://huggingface.co/${{ secrets.HF_USERNAME }}/LongRoPE
                  git push huggingface master:main --force
