name: Sync with Hugging Face

on:
    push:
        branches:
            - main

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Git
              run: sudo apt-get install git-lfs
            - name: Install Hugging Face Hub
              run: pip install huggingface_hub
            - name: Sync to Hugging Face
              env:
                  HF_TOKEN: ${{ secrets.HF_TOKEN }}
              run: |
                  git lfs install
                  huggingface-cli login --token $HF_TOKEN
                  git push https://huggingface.co/jshuadvd/LongRoPE main
